FROM flowable/flowable-admin:6.4.2.1
ENV MYSQL_VERSION 8.0.18
RUN cd /opt/jdk/jre/lib && \
    wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_VERSION}/mysql-connector-java-${MYSQL_VERSION}.jar