spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable
server:
  port: 8081
  servlet:
    context-path: /api
flowable:
  deployment-name: 测试流程
  form:
    deployment-name: 测试表单
logging:
  level:
    com.example: debug