spring:
  datasource:
    username: flowable
    password: flowable
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/flowable
server:
  port: 8081
  servlet:
    context-path: /api
flowable:
  deployment-name: 测试流程
  form:
    deployment-name: 测试表单
logging:
  level:
    com.example: debug